# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       baloo

# >> macros
# << macros

Summary:    Library for indexing and search
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  baloo.yaml
Source101:  baloo-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kdelibs4support-devel
BuildRequires:  kfilemetadata-devel
BuildRequires:  libxapian-devel
BuildRequires:  kidletime-devel
BuildRequires:  kcmutils-devel
BuildRequires:  krunner-devel

%description
Library for indexing and search


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_kf5_libdir}/*.so.*
%{_kf5_plugindir}/*
%{_kf5_bindir}/*
%{_kf5_configdir}/autostart/baloo_file.desktop
%{_kf5_sysconfdir}/dbus-1/system.d/org.kde.baloo.filewatch.conf
%{_kf5_libdir}/libexec/kauth/kde_baloo_filewatch_raiselimit
%{_kf5_sharedir}/dbus-1/system-services/org.kde.baloo.filewatch.service
%{_kf5_servicesdir}/*
%{_kf5_sharedir}/polkit-1/actions/org.kde.baloo.filewatch.policy
%{_kf5_sharedir}/icons/hicolor/*/apps/baloo.png
%{_kf5_qmldir}/*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_libdir}/*.so
%{_kf5_cmakedir}/KF5Baloo
%{_kf5_includedir}/baloo_version.h
%{_kf5_includedir}/Baloo/*
%{_kf5_dbusinterfacesdir}/*
# >> files devel
# << files devel
